pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '11.12.0'
    displayName: 'Install Node.js'

  - script: yarn install
    displayName: 'Install dependencies'

  - script: yarn lint:check
    displayName: 'Linter check'

  - script: yarn typecheck
    displayName: 'Typecheck'

  - script: yarn test:ci
    displayName: 'Test'

  - script: yarn upload-coverage
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
    displayName: 'Upload coverage report'

  - script: yarn semantic-release
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      NPM_TOKEN: $(NPM_TOKEN)
    displayName: 'Release'

variables:
  CI: true
